### PR TITLE
Fixes #100

### LINKED ISSUE #100: New fields for window object are not deep copied on assignment
Consider this example where:
```
var obj = {a: {b: 1}}
window.obj = obj
window.obj.a.b
```
This fails because the call to `window.obj.a` returns `undefined`.

### PR DESCRIPTION
**Pull request by rachitnigam**

### CODE REVIEW

**Comment by arjunguha** [comment]
Doesn't build?

**Comment by arjunguha** [comment]
Oh, I see. values set on window are now trusted!

This is not a problem. We can update tests and merge in.

**Comment by rachitnigam** [comment]
Um, yeah. There is an issue. Probably that the jswindow reference is a facet when it should be a object.

-----
Rachit Nigam
University of Massachusetts, Amherst - Class of 2019
Computer Science and Mathematics Major
rachit.nigam12@gmail.com <mailto:rachit.nigam12@gmail.com> | 413-406-8526

“Sometimes it is the people no one can imagine anything of who do the things no one can imagine.”  ― Alan Turing

**Comment by rachitnigam** [comment]
Aren't writes to window required to be untrusted according to our semantics?

**Comment by arjunguha** [comment]
Did you not understand my first comment? I think it's okay that the tests are breaking. The tests need to be updated. Do you agree?

**Comment by rachitnigam** [comment]
I am not entirely sure since the jswindow isn't explicitly wrapped in a VFacet. Is it because jswindow is a reference on the client?

**Comment by arjunguha** [comment]
Correct. You don't need to wrap it. It is wrapped because it comes from the client

**Comment by rachitnigam** [comment]
So functions like `hasOwnProperty` don't work on window anymore because of the hack. `hasOwnProperty` doesn't check the `__ proto__` for the field which makes the behaviour incorrect on window.

**Pull request closed without merging**
