### PR TITLE
Drop the name of a function that is assigned to a variable. (Fixes #96)

### LINKED ISSUE #96: Named function assigned to variable
The following errors:
```
var p = function foo(x) { return x; }
p(1)
```
with `foo not defined`.

This does not:
```
var p = function(x) {return x; }
p(1)
```

Quick fix would be to drop the name, but not sure if that is semantically consistent with JS.

### PR DESCRIPTION
**Pull request by rachitnigam**
```
  var p = function foo(x) { return x; }
  p(1)
```
is the same as
```
  var p = function(x) { return x; }
  p(1)
```

### CODE REVIEW

**Comment by arjunguha** [comment]
Sorry, this is not quite right. (The old behavior may have also been wrong.)

You can refer to `foo` in the body of the function in the first example. Does this show up in Elm or somewhere else?

**Comment by rachitnigam** [comment]
Yes, I realized this while I was eating pizza. Took all the fun out of it.

**Comment by rachitnigam** [comment]
It shows up in two places in elm, both of which can easily be fixed by removing the function name.

**Comment by arjunguha** [comment]
Remarkable. I'm about to order pizza too.

**Pull request closed without merging**
